### ISSUE TITLE
having trouble compiling

### ISSUE THREAD

**Issue by janet413** [StevePaget/Pygame_Functions#21]
Hi,
I just found your videos and library and thought they would be ideal for a introductory python class I am currently teaching. I downloaded the most recent pygame_functions and tried to compile but I am getting this error from the library and I am stumped. Any suggestions?

Thanks,
Janet

Traceback (most recent call last):

  File "<ipython-input-2-1532a53440b1>", line 1, in <module>
    runfile('/Users/jslocum/Desktop/makinggames/bunny&carrot.py', wdir='/Users/jslocum/Desktop/makinggames')

  File "/Users/jslocum/anaconda3/lib/python3.5/site-packages/spyder_kernels/customize/spydercustomize.py", line 668, in runfile
    execfile(filename, namespace)

  File "/Users/jslocum/anaconda3/lib/python3.5/site-packages/spyder_kernels/customize/spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/Users/jslocum/Desktop/makinggames/bunny&carrot.py", line 25, in <module>
    moveSprite(bunny,10,height/2)

  File "/Users/jslocum/Desktop/makinggames/pygame_functions.py", line 313, in moveSprite
    updateDisplay()

  File "/Users/jslocum/Desktop/makinggames/pygame_functions.py", line 674, in updateDisplay
    spriteRects = spriteGroup.draw(screen)

  File "/Users/jslocum/anaconda3/lib/python3.5/site-packages/pygame/sprite.py", line 568, in draw
    surface_blit = surface.blit

AttributeError: 'str' object has no attribute 'blit'

In case its my code

import pygame, sys, random
from pygame.locals import *
from pygame_functions import *    

pygame.init()

FPS = 300 # frames per second setting
fpsClock = pygame.time.Clock()

grassImg = pygame.image.load('grass.bmp')

width = grassImg.get_width()    #find the width of the image
height = grassImg.get_height()   #find the height of the image

# set up the window
DISPLAYSURF = pygame.display.set_mode((width, height), 0, 32)
pygame.display.set_caption('Animation')

pygame.time.set_timer ( pygame.USEREVENT , 1000 )

#catImg = pygame.image.load('cat.bmp')
bunny = makeSprite('cat.bmp')
moveSprite(bunny,10,height/2)
showSprite(bunny)
carrot = []
speed =[]
location = []
for i in range(5):
    carrot.append(makeSprite(carrot.bmp))
    speedx = random.randomint(1,5)
    speedy = random.randomint(1,5)
    speed.append((speedx,speedy))
    location.append((random.randomint(0,1000),random.randomint(0,500)))
    moveSprite(carrot[i],location[i][0],location[i][1])
    showSprite(carrot[i])

**Comment by janet413** [comment]
Thanks
I was clearly mixing my metaphors. Got it now.
