### ISSUE TITLE
pygame_functions: Text outputs ad inputs

### ISSUE THREAD

**Issue by gjanosz** [StevePaget/Pygame_Functions#4]
Hi Steve,
I've installed Pygame_Functions and I'm experimenting with the code from your Text Outputs and Inputs lesson.  It's named text.py
*******************************************
import pygame
from pygame_functions import *
import random

size = [790, 600]
instructionLabel = makeLabel("Please enter a word", 40, 10, 40, ("blue"), "AZgency FB", 'yellow')
showLabel(instructionLabel)
****************************************
But I get the following error message:

C:\Users\gjano>text.py
Traceback (most recent call last):
  File "C:\Users\gjano\text.py", line 13, in <module>
    showLabel(instructionLabel)
  File "C:\Users\gjano\pygame_functions.py", line 562, in showLabel
    updateDisplay()
  File "C:\Users\gjano\pygame_functions.py", line 582, in updateDisplay
    spriteRects = spriteGroup.draw(screen)
  File "C:\Users\gjano\AppData\Roaming\Python\Python36\site-packages\pygame\sprite.py", line 568, in draw
    surface_blit = surface.blit
AttributeError: 'str' object has no attribute 'blit'

**Comment by gjanosz** [comment]
Please disregard pygame_functions: Text outputs ad inputs #4.  User error!

**Comment by gjanosz** [comment]
Hi Steve,  I'm working on the code for a device I'm inventing that keeps track of all aspects of American Football most importantly field position.  My game console is designed to be used in a limited space, but simulate the movement down a 100 yard field.  The line of scrimmage stays constant, after each play the device measures the distance and angle in degrees to the ball and uses that as input for the console which in turn displays the down, yards to go to a 1st down, field position and score.  Right now I'm simulating the inputs with entries to the command line.  I'm attempting to use your software to make all entries from the display.  Here's the code to date.  
[scoreboard.pdf](https://github.com/StevePaget/Pygame_Functions/files/1258319/scoreboard.pdf)
